steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file
      - deploy/ama-cloud/Dockerfile
      - --tag
      - ${_IMAGE}
      - .
    timeout: 3600s
  - name: gcr.io/cloud-builders/docker
    args: [push, '${_IMAGE}']
    timeout: 3600s
images:
  - '${_IMAGE}'
timeout: 7200s
options:
  machineType: E2_HIGHCPU_8
  diskSizeGb: 100
substitutions:
  _IMAGE: asia-southeast1-docker.pkg.dev/example/ama-cloud/ama-cloud-01:unset
